version: '2.1'

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

machine: &machine
  # Run docker-compose on the VM
  machine:
    image: circleci/classic:201808-01
    docker_layer_caching: true
  working_directory: /tmp/workspace/project

jobs:
  test:
    <<: *machine
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test-in-docker

workflows:
  build-and-push:
    jobs:
      - test
