#!/bin/bash
# Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# This script is meant to make all package available in the 'canonical' location
# when running on a remote CI machine

if [[ ! -d "${GOPATH}/src/github.com/aws/amazon-ecs-init" ]]; then
	mkdir -p "${GOPATH}/src/github.com/aws"
  echo "Symlinking $(pwd) to ${GOPATH}/src/github.com/aws/amazon-ecs-init"
	ln -s "$(pwd)" "${GOPATH}/src/github.com/aws/amazon-ecs-init"
fi
